# Handling Imbalanced Dataset

### up sampling 
### down sampling

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# set the random seed for reproductivity 
np.random.seed(123)

# create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0, n_class_1

(900, 100)

In [4]:
class_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [8]:
pd.concat([class_0,class_1]).reset_index(drop=True)

     feature1  feature2  target
0   -1.085631  0.551302       0
1    0.997345  0.419589       0
2    0.282978  1.815652       0
3   -1.506295 -0.252750       0
4   -0.578600 -0.292004       0
..        ...       ...     ...
995 -0.623629  0.845701       1
996  0.239810 -1.119923       1
997 -0.868240 -0.359297       1
998  0.902006 -1.609695       1
999  0.697490  0.013570       1

[1000 rows x 3 columns]

In [9]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [10]:
df.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [11]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## upsampling

In [15]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [16]:
df_minority.head()

     feature1  feature2  target
900 -0.300232  0.139033       1
901 -0.632261  0.025577       1
902 -0.204317 -0.196443       1
903  0.213696  1.312255       1
904  1.033878  1.187417       1

In [17]:
df_majority.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [27]:
##Upsampling perform
from sklearn.utils import resample

In [31]:
df_minority_upsample= resample(df_minority,
                                 replace=True, # sample with replacement
                                 n_samples=len(df_majority),# to match the majority class
                                 random_state=42
                                )

In [32]:
df_minority_upsample.shape

(900, 3)

In [33]:
df_minority_upsample.head()

     feature1  feature2  target
951 -0.874146 -0.156083       1
992  0.196570 -0.602575       1
914 -0.067830  0.998053       1
971  0.272825  1.034197       1
960  0.870056 -0.449515       1

In [34]:
df_minority_upsample.value_counts()

feature1   feature2   target
-0.994810  -0.889911  1         19
-0.084530  -0.347959  1         18
 1.701608   0.160889  1         18
 0.902006  -1.609695  1         16
 1.013493   0.047240  1         16
                                ..
-1.011644  -0.164875  1          4
 0.995595   0.475934  1          4
 0.013560   0.847260  1          4
 0.549697   1.095922  1          4
-0.754008   0.946908  1          3
Name: count, Length: 100, dtype: int64

In [35]:
df_minority_upsample['target'].value_counts()

target
1    900
Name: count, dtype: int64

In [36]:
df_upsampled= pd.concat([df_majority,df_minority_upsample])

In [37]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [38]:
df_upsampled.head()

   feature1  feature2  target
0 -1.085631  0.551302       0
1  0.997345  0.419589       0
2  0.282978  1.815652       0
3 -1.506295 -0.252750       0
4 -0.578600 -0.292004       0

In [39]:
df_upsampled.tail()

     feature1  feature2  target
952 -0.811098  0.189189       1
965  1.919526 -0.019459       1
976  0.810326  1.604614       1
942  1.621531  0.168229       1
974 -0.839113  0.489203       1

In [40]:
df_upsampled.shape

(1800, 3)

## Down sampling

In [43]:
class_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [44]:
pd.concat([class_0,class_1]).reset_index(drop=True)

     feature1  feature2  target
0   -0.471276  0.328462       0
1    1.084072  1.038230       0
2   -0.379223  1.147064       0
3   -0.362274  0.638254       0
4   -0.681071 -1.075766       0
..        ...       ...     ...
995  0.720690 -0.021511       1
996 -0.050922  1.709793       1
997  0.709784  1.324917       1
998 -0.182311 -0.450763       1
999  0.838910  0.240773       1

[1000 rows x 3 columns]

In [45]:
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [46]:
df_majority_downsample= resample(df_majority,
                                 replace=False, # sample without replacement
                                 n_samples=len(df_minority),# to match the minority class
                                 random_state=42
                                )

In [47]:
df_majority_downsample.shape

(100, 3)

In [48]:
pd.concat([df_minority, df_majority_downsample])

     feature1  feature2  target
900 -0.300232  0.139033       1
901 -0.632261  0.025577       1
902 -0.204317 -0.196443       1
903  0.213696  1.312255       1
904  1.033878  1.187417       1
..        ...       ...     ...
398 -0.168426  0.553775       0
76  -0.403366  0.081491       0
196 -0.269293  0.611238       0
631 -0.295829  0.671673       0
751 -0.553404  0.804438       0

[200 rows x 3 columns]

In [49]:
pd.concat([df_minority, df_majority_downsample]).value_counts()

feature1   feature2   target
-2.251535  -0.382087  0         1
-2.187086   0.499457  0         1
-2.152493  -0.518353  0         1
-2.124575   0.145717  1         1
-2.008585  -0.422115  0         1
                               ..
 1.919526  -0.019459  1         1
 1.984582  -0.682331  0         1
 2.125817  -0.215410  1         1
 2.559850  -0.085205  0         1
 3.571579   0.850721  0         1
Name: count, Length: 200, dtype: int64

In [50]:
df_downsample = pd.concat([df_minority, df_majority_downsample])

In [51]:
df_downsample['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64