# NOMINAL /  ONE HOT ENCODING

In [3]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [5]:
# create a sample dataset with a categorical variables
df= pd.DataFrame({
    'colour' : ['red', 'blue','green', 'green','red','blue']
})

In [6]:
df

  colour
0    red
1   blue
2  green
3  green
4    red
5   blue

In [19]:
# create an instance of one hot encoder
encoder= OneHotEncoder()

In [20]:
encoded= encoder.fit_transform(df[['colour']])

In [22]:
import pandas as pd
pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

   colour_blue  colour_green  colour_red
0          0.0           0.0         1.0
1          1.0           0.0         0.0
2          0.0           1.0         0.0
3          0.0           1.0         0.0
4          0.0           0.0         1.0
5          1.0           0.0         0.0

In [25]:
encoder.get_feature_names_out()

array(['colour_blue', 'colour_green', 'colour_red'], dtype=object)

In [26]:
encoded_df=pd.DataFrame(encoded.toarray(),columns=encoder.get_feature_names_out())

In [27]:
encoded_df

   colour_blue  colour_green  colour_red
0          0.0           0.0         1.0
1          1.0           0.0         0.0
2          0.0           1.0         0.0
3          0.0           1.0         0.0
4          0.0           0.0         1.0
5          1.0           0.0         0.0

In [28]:
pd.concat([df,encoded_df],axis=1)

  colour  colour_blue  colour_green  colour_red
0    red          0.0           0.0         1.0
1   blue          1.0           0.0         0.0
2  green          0.0           1.0         0.0
3  green          0.0           1.0         0.0
4    red          0.0           0.0         1.0
5   blue          1.0           0.0         0.0