# Target Guided Ordinal Encoding

In [1]:
import pandas as pd

In [2]:
# create a sample dataframe with a  catogorical variable and a target variable
df = pd.DataFrame({
    'city' : ['New york','London','Paris','Tokyo','New york','Paris'],
    'price' : [200,150,300,250,180,320]
})

In [3]:
df.head()

       city  price
0  New york    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New york    180

In [6]:
# calculate the mean price for each city
df.groupby('city')['price'].mean()

city
London      150.0
New york    190.0
Paris       310.0
Tokyo       250.0
Name: price, dtype: float64

In [7]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [8]:
## replace each city with its mean price
df['city_encoded']= df['city'].map(mean_price)

In [9]:
df

       city  price  city_encoded
0  New york    200         190.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New york    180         190.0
5     Paris    320         310.0